development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

travis:
  adapter: mysql2
  database: statusbot_test
  username: travis
  encoding: utf8
